#!/usr/bin/env Rscript
# Emit the LaTeX hierarchy synopsis table from the rich diagnostics overview,
# picking the best model per dataset.
suppressPackageStartupMessages({
  library(readr); library(dplyr)
})

RUN_DIR <- Sys.getenv("APP_RUN_DIR",
  unset = "output/application/raw/application_run_20260414_104327")
OUT_DIR <- Sys.getenv("APP_PAPER_TABLES_DIR",
  unset = file.path("output/paper/tables", basename(RUN_DIR)))
overview <- read_csv("output/application/tables/hierarchy_diagnostics_overview.csv",
                     show_col_types = FALSE)

# Best model per dataset (matches the LOO winner narrative)
BEST <- c(moreno_sheep   = "SST",
          strauss_2019b  = "WST",
          mountain_goats = "SST",
          citations_data = "DCSBM",
          macaques_data  = "DCSBM",
          high_school    = "SST")

LABEL <- c(moreno_sheep   = "Bighorn sheep",
           strauss_2019b  = "Spotted hyenas",
           mountain_goats = "Mountain goats",
           citations_data = "Stat.\\ journals",
           macaques_data  = "Japanese macaques",
           high_school    = "High school")

MODEL_LABEL <- c(WST = "WST", SST = "Toeplitz SST", DCSBM = "DC--SBM")
N <- c(moreno_sheep = 28, strauss_2019b = 35, mountain_goats = 45,
       citations_data = 47, macaques_data = 62, high_school = 70)

ORDER <- c("moreno_sheep", "strauss_2019b", "mountain_goats",
           "macaques_data", "citations_data", "high_school")

fmt_pct <- function(x) ifelse(is.na(x), "--", sprintf("$%.1f\\%%$", 100 * x))
fmt_int <- function(x) ifelse(is.na(x), "--", formatC(round(x), format = "d", big.mark = "{,}"))
fmt_pct_count <- function(rate, back, cross) {
  ifelse(is.na(rate), "--", sprintf("$%.1f\\%%$ (%s/%s)", 100 * rate, fmt_int(back), fmt_int(cross)))
}
fmt_two <- function(x) ifelse(is.na(x), "--", sprintf("$%.2f$", x))

rows <- character(0)
for (ds in ORDER) {
  m  <- BEST[[ds]]
  r  <- overview[overview$dataset == ds & overview$fit_model == m, ]
  rows <- c(rows, paste(
    LABEL[[ds]], N[[ds]], MODEL_LABEL[[m]], r$K_hat,
    fmt_pct_count(r$violation_rate_zhat, r$violation_count_zhat, r$cross_count_zhat),
    fmt_two(r$thetaW_block_emp_mean),
    fmt_two(r$thetaS_block_emp_mean),
    fmt_two(r$bar_rho_model_mean),
    sep = " & "
  ))
}

tex <- c(
  "% Auto-generated by scripts/analysis/build_hierarchy_synopsis_table.R",
  "\\begin{tabular}{lccccccc}",
  "\\toprule",
  "Dataset & $n$ & Best model & $K$",
  "  & $\\zeta^{\\mathrm{viol}}_{\\hat z}$ (back/cross)",
  "  & $\\bar\\zeta_W^{\\mathrm{blk}}$",
  "  & $\\bar\\zeta_S^{\\mathrm{blk}}$",
  "  & $\\bar\\rho$ \\\\",
  "\\midrule",
  paste0(rows, " \\\\"),
  "\\bottomrule",
  "\\end{tabular}"
)
out_path <- file.path(OUT_DIR, "hierarchy_synopsis_paper.tex")
writeLines(tex, out_path)
cat("Wrote:", out_path, "\n")
