#!/usr/bin/env Rscript
# Build application-study supplement tables that are not part of the main text.
#
# Outputs:
#   output/paper/tables/<run_id>/application_psis_diagnostics.{csv,tex}
#   output/paper/tables/<run_id>/application_cycle_diagnostics.{csv,tex}
#   output/paper/tables/<run_id>/application_high_school_cycle_inspection.{csv,tex}

suppressPackageStartupMessages({
  library(dplyr)
  library(readr)
})

RUN_DIR <- Sys.getenv(
  "APP_RUN_DIR",
  unset = "output/application/raw/application_run_20260414_104327"
)
if (!dir.exists(RUN_DIR)) {
  stop("APP_RUN_DIR does not exist: ", RUN_DIR, call. = FALSE)
}

RUN_ID <- basename(RUN_DIR)
OUT_DIR <- Sys.getenv(
  "APP_PAPER_TABLES_DIR",
  unset = file.path("output", "paper", "tables", RUN_ID)
)
dir.create(OUT_DIR, recursive = TRUE, showWarnings = FALSE)

DATASET_ORDER <- c(
  "moreno_sheep", "strauss_2019b", "mountain_goats",
  "citations_data", "macaques_data", "high_school"
)
DATASET_LABEL <- c(
  moreno_sheep   = "Bighorn sheep",
  strauss_2019b  = "Spotted hyenas",
  mountain_goats = "Mountain goats",
  citations_data = "Stat.\\ journals",
  macaques_data  = "Macaques",
  high_school    = "High school"
)
MODEL_ORDER <- c("WST", "SST", "DCSBM")
MODEL_LABEL <- c(
  WST = "WST--OSBM",
  SST = "Toeplitz SST--OSBM",
  DCSBM = "DC--SBM"
)
POINT_SOURCE_LABEL <- c(
  Agony = "Agony",
  WST = "WST--OSBM",
  SST = "Toeplitz SST--OSBM",
  DCSBM = "DC--SBM"
)

fmt_num <- function(x, digits = 1) {
  ifelse(is.na(x), "---",
         formatC(round(x, digits), format = "f",
                 digits = digits, big.mark = "{,}"))
}
fmt_pct <- function(x, digits = 1) {
  ifelse(is.na(x), "---",
         paste0(formatC(100 * x, format = "f", digits = digits), "\\%"))
}
fmt_pct_small <- function(x) {
  ifelse(
    is.na(x), "---",
    ifelse(x > 0 & x < 0.001, "<0.1\\%", fmt_pct(x, 1))
  )
}
fmt_int <- function(x) {
  ifelse(is.na(x), "---", formatC(as.integer(round(x)), format = "d",
                                  big.mark = "{,}"))
}
fmt_count_pct <- function(count, total) {
  if (is.na(count) || is.na(total) || total <= 0) return("---")
  sprintf("$%s/%s$ (%s)", fmt_int(count), fmt_int(total), fmt_pct_small(count / total))
}
fmt_mass_range <- function(lo, hi) {
  if (is.na(lo) || is.na(hi)) return("---")
  if (lo == hi) return(sprintf("$%s$", fmt_int(lo)))
  sprintf("$%s$--$%s$", fmt_int(lo), fmt_int(hi))
}

ensure_application_helpers <- function() {
  if (!exists("choose_dataset_local", mode = "function") ||
      !exists("get_z_hat_from_draws", mode = "function")) {
    suppressPackageStartupMessages({
      source("scripts/analysis/osbm_visualization.R", chdir = FALSE)
    })
  }
}

read_all_results <- function(path) {
  first <- readLines(path, n = 1L)
  if (grepl("dataset", first)) {
    readr::read_csv(path, show_col_types = FALSE)
  } else {
    readr::read_csv(
      path, show_col_types = FALSE,
      col_names = c("dataset", "fit_model", "K_hat", "K_mean", "K_lo", "K_hi",
                    "elpd_loo", "p_loo", "looic", "pk_max", "pk_bad",
                    "b_kappa", "time_sec", "note")
    )
  }
}

build_psis_table <- function() {
  all_res_path <- file.path(RUN_DIR, "all_results.csv")
  if (!file.exists(all_res_path)) {
    stop("Missing all_results.csv in ", RUN_DIR, call. = FALSE)
  }

  res <- read_all_results(all_res_path) |>
    filter(dataset %in% DATASET_ORDER, fit_model %in% MODEL_ORDER) |>
    mutate(
      dataset = factor(dataset, levels = DATASET_ORDER),
      fit_model = factor(fit_model, levels = MODEL_ORDER)
    ) |>
    arrange(dataset, fit_model)

  csv_tbl <- res |>
    transmute(
      dataset = as.character(dataset),
      model = as.character(fit_model),
      K_hat, elpd_loo, p_loo, looic,
      pareto_k_max = pk_max,
      pareto_k_gt_0_7 = pk_bad
    )
  readr::write_csv(csv_tbl, file.path(OUT_DIR, "application_psis_diagnostics.csv"))

  rows <- character(0)
  prev_ds <- NA_character_
  for (i in seq_len(nrow(res))) {
    row <- res[i, ]
    ds_key <- as.character(row$dataset)
    model_key <- as.character(row$fit_model)
    ds_cell <- if (!identical(ds_key, prev_ds)) {
      sprintf("\\multirow{3}{*}{%s}", DATASET_LABEL[[ds_key]])
    } else {
      ""
    }
    rows <- c(rows, sprintf(
      "%s & %s & $%d$ & $%s$ & $%s$ & $%s$ & $%s$ \\\\",
      ds_cell,
      MODEL_LABEL[[model_key]],
      as.integer(row$K_hat),
      fmt_num(row$elpd_loo, 1),
      fmt_num(row$p_loo, 1),
      fmt_num(row$pk_max, 2),
      fmt_pct(row$pk_bad, 1)
    ))
    if (i %% 3L == 0L && i < nrow(res)) rows <- c(rows, "\\addlinespace")
    prev_ds <- ds_key
  }

  lines <- c(
    "% Auto-generated by scripts/analysis/build_application_supplement_tables.R",
    "% Do NOT edit by hand.",
    "\\begin{table}[htbp]",
    "\\centering",
    "\\small",
    "\\setlength{\\tabcolsep}{5pt}",
    "\\begin{tabular}{@{}llrrrrr@{}}",
    "\\toprule",
    "Dataset & Model & $\\hat K$ & ELPD$_{\\mathrm{loo}}$ & $p_{\\mathrm{loo}}$ & max $k$ & $\\Pr(k>0.7)$ \\\\",
    "\\midrule",
    rows,
    "\\bottomrule",
    "\\end{tabular}",
    paste0(
      "\\caption{PSIS--LOO diagnostics for the application fits. ",
      "The last column is the empirical proportion of pointwise Pareto ",
      "$k$ diagnostics above 0.7; values are computed from the dyad-level ",
      "log-likelihood matrix used for the LOO comparison in the main text.}"
    ),
    "\\label{tab:application-psis-diagnostics}",
    "\\end{table}"
  )
  writeLines(lines, file.path(OUT_DIR, "application_psis_diagnostics.tex"))
}

compact_partition_labels_local <- function(z) {
  lev <- sort(unique(as.integer(z[!is.na(z)])))
  map <- setNames(seq_along(lev), as.character(lev))
  as.integer(map[as.character(as.integer(z))])
}

block_weight_matrix_local <- function(A, z) {
  z <- compact_partition_labels_local(z)
  K <- max(z, na.rm = TRUE)
  W <- matrix(0, K, K)
  for (i in seq_len(nrow(A))) {
    for (j in seq_len(ncol(A))) {
      if (i == j || A[i, j] <= 0) next
      W[z[i], z[j]] <- W[z[i], z[j]] + A[i, j]
    }
  }
  W
}

cycle_details_from_partition <- function(A, z) {
  W <- block_weight_matrix_local(A, z)
  K <- nrow(W)
  Tmat <- matrix(FALSE, K, K)
  pair_rows <- list()
  pair_id <- 0L
  ties <- 0L
  oriented <- 0L
  reversed <- 0L
  if (K >= 2L) {
    for (a in seq_len(K - 1L)) {
      for (b in (a + 1L):K) {
        pair_id <- pair_id + 1L
        total_ab <- W[a, b] + W[b, a]
        forward_share <- if (total_ab > 0) W[a, b] / total_ab else NA_real_
        orientation <- "tie"
        if (W[a, b] > W[b, a]) {
          Tmat[a, b] <- TRUE
          oriented <- oriented + 1L
        } else if (W[b, a] > W[a, b]) {
          Tmat[b, a] <- TRUE
          oriented <- oriented + 1L
          reversed <- reversed + 1L
          orientation <- "backward"
        } else {
          ties <- ties + 1L
        }
        if (W[a, b] > W[b, a]) orientation <- "forward"
        pair_rows[[pair_id]] <- data.frame(
          from = a,
          to = b,
          forward_mass = W[a, b],
          backward_mass = W[b, a],
          total_mass = total_ab,
          forward_share = forward_share,
          orientation = orientation,
          stringsAsFactors = FALSE
        )
      }
    }
  }

  cyclic_triples <- 0L
  n_triples <- if (K >= 3L) choose(K, 3) else 0
  cycle_rows <- list()
  cycle_id <- 0L
  if (K >= 3L) {
    for (a in seq_len(K - 2L)) {
      for (b in (a + 1L):(K - 1L)) {
        for (c in (b + 1L):K) {
          cyc_abc <- Tmat[a, b] && Tmat[b, c] && Tmat[c, a]
          cyc_acb <- Tmat[a, c] && Tmat[c, b] && Tmat[b, a]
          if (cyc_abc || cyc_acb) {
            cyclic_triples <- cyclic_triples + 1L
            mass_ab <- W[a, b] + W[b, a]
            mass_ac <- W[a, c] + W[c, a]
            mass_bc <- W[b, c] + W[c, b]
            cycle_id <- cycle_id + 1L
            cycle_rows[[cycle_id]] <- data.frame(
              a = a,
              b = b,
              c = c,
              orientation = if (cyc_abc) {
                sprintf("%d>%d>%d>%d", a, b, c, a)
              } else {
                sprintf("%d>%d>%d>%d", a, c, b, a)
              },
              mass_ab = mass_ab,
              mass_ac = mass_ac,
              mass_bc = mass_bc,
              min_pair_mass = min(mass_ab, mass_ac, mass_bc),
              max_pair_mass = max(mass_ab, mass_ac, mass_bc),
              stringsAsFactors = FALSE
            )
          }
        }
      }
    }
  }

  any_cycle <- FALSE
  if (K >= 2L && any(Tmat)) {
    graph <- igraph::graph_from_adjacency_matrix(
      Tmat + 0L, mode = "directed", diag = FALSE
    )
    any_cycle <- !igraph::is_dag(graph)
  }

  total_pairs <- if (K >= 2L) choose(K, 2) else 0
  pair_df <- if (length(pair_rows)) bind_rows(pair_rows) else data.frame()
  cycle_df <- if (length(cycle_rows)) bind_rows(cycle_rows) else data.frame()

  list(
    summary = data.frame(
      K = K,
      any_cycle = any_cycle,
      cyclic_triples = cyclic_triples,
      total_triples = n_triples,
      cyclic_triple_share = if (n_triples > 0) cyclic_triples / n_triples else NA_real_,
      total_pairs = total_pairs,
      oriented_pairs = oriented,
      tied_pairs = ties,
      reversed_pairs = reversed,
      reversed_pair_share = if (total_pairs > 0) reversed / total_pairs else NA_real_
    ),
    pairs = pair_df,
    cycles = cycle_df
  )
}

cycle_summary_from_partition <- function(A, z) {
  cycle_details_from_partition(A, z)$summary
}

build_cycle_table <- function() {
  ensure_application_helpers()

  rows <- list()
  for (ds in DATASET_ORDER) {
    A <- choose_dataset_local(ds)
    if (inherits(A, "Matrix")) A <- as.matrix(A)

    agony_fit <- solve_agony_partition(A, timeout = 60L)
    rows[[length(rows) + 1L]] <- cbind(
      data.frame(dataset = ds, source = "Agony", stringsAsFactors = FALSE),
      cycle_summary_from_partition(A, agony_fit$ranks)
    )

    for (model in MODEL_ORDER) {
      fit_path <- file.path(RUN_DIR, paste0(ds, "_", model, "_fit.rds"))
      if (!file.exists(fit_path)) next
      fit <- readRDS(fit_path)
      z_hat <- get_z_hat_from_draws(fit, A, model = model)$z_hat
      rows[[length(rows) + 1L]] <- cbind(
        data.frame(dataset = ds, source = model, stringsAsFactors = FALSE),
        cycle_summary_from_partition(A, z_hat)
      )
    }
  }

  out <- bind_rows(rows) |>
    mutate(
      dataset = factor(dataset, levels = DATASET_ORDER),
      source = factor(source, levels = c("Agony", "WST", "SST", "DCSBM"))
    ) |>
    arrange(dataset, source)

  readr::write_csv(out, file.path(OUT_DIR, "application_cycle_diagnostics.csv"))

  yes_no <- function(x) ifelse(isTRUE(x), "Yes", "No")

  tex_rows <- character(0)
  prev_ds <- NA_character_
  for (i in seq_len(nrow(out))) {
    row <- out[i, ]
    ds_key <- as.character(row$dataset)
    source_key <- as.character(row$source)
    ds_cell <- if (!identical(ds_key, prev_ds)) {
      sprintf("\\multirow{4}{*}{%s}", DATASET_LABEL[[ds_key]])
    } else {
      ""
    }
    tex_rows <- c(tex_rows, sprintf(
      "%s & %s & $%d$ & %s & $%s/%s$ & $%s$ & $%d$ \\\\",
      ds_cell,
      POINT_SOURCE_LABEL[[source_key]],
      as.integer(row$K),
      yes_no(row$any_cycle),
      fmt_int(row$cyclic_triples),
      fmt_int(row$total_triples),
      fmt_pct_small(row$cyclic_triple_share),
      as.integer(row$tied_pairs)
    ))
    if (i %% 4L == 0L && i < nrow(out)) tex_rows <- c(tex_rows, "\\addlinespace")
    prev_ds <- ds_key
  }

  lines <- c(
    "% Auto-generated by scripts/analysis/build_application_supplement_tables.R",
    "% Do NOT edit by hand.",
    "\\begin{table}[htbp]",
    "\\centering",
    "\\small",
    "\\setlength{\\tabcolsep}{5pt}",
    "\\begin{tabular}{@{}llrcrrr@{}}",
    "\\toprule",
    "Dataset & Point estimate & $K$ & Any cycle & Cyclic triples & Share & Tied pairs \\\\",
    "\\midrule",
    tex_rows,
    "\\bottomrule",
    "\\end{tabular}",
    paste0(
      "\\caption{Cycle diagnostics for application point estimates. ",
      "For each partition we aggregate observed directed mass between blocks ",
      "and orient each unordered block pair toward the larger flow; exact ties ",
      "are left unoriented. `Any cycle' reports whether this majority-flow ",
      "block graph is non-acyclic, and cyclic triples counts directed ",
      "3-cycles among block triples. The share is the unweighted proportion ",
      "of the \\(\\binom{K}{3}\\) block triples that are cyclic. The WST, ",
      "Toeplitz SST and DC--SBM ",
      "point estimates use \\texttt{minVI} with \\texttt{method=draws}; ",
      "DC--SBM draws are strength-reordered before the point estimate is formed.}"
    ),
    "\\label{tab:application-cycle-diagnostics}",
    "\\end{table}"
  )
  writeLines(lines, file.path(OUT_DIR, "application_cycle_diagnostics.tex"))
}

build_high_school_cycle_inspection_table <- function() {
  ensure_application_helpers()

  A <- choose_dataset_local("high_school")
  if (inherits(A, "Matrix")) A <- as.matrix(A)

  partitions <- list(Agony = solve_agony_partition(A, timeout = 60L)$ranks)
  for (model in MODEL_ORDER) {
    fit_path <- file.path(RUN_DIR, paste0("high_school_", model, "_fit.rds"))
    if (!file.exists(fit_path)) next
    fit <- readRDS(fit_path)
    partitions[[model]] <- get_z_hat_from_draws(fit, A, model = model)$z_hat
  }

  rows <- list()
  for (source_key in names(partitions)) {
    details <- cycle_details_from_partition(A, partitions[[source_key]])
    s <- details$summary
    cycle_min <- if (nrow(details$cycles)) min(details$cycles$min_pair_mass) else NA_real_
    cycle_min_hi <- if (nrow(details$cycles)) max(details$cycles$min_pair_mass) else NA_real_
    rows[[length(rows) + 1L]] <- data.frame(
      source = source_key,
      K = s$K,
      reversed_pairs = s$reversed_pairs,
      total_pairs = s$total_pairs,
      reversed_pair_share = s$reversed_pair_share,
      tied_pairs = s$tied_pairs,
      cyclic_triples = s$cyclic_triples,
      total_triples = s$total_triples,
      cyclic_triple_share = s$cyclic_triple_share,
      weakest_cycle_pair_mass_min = cycle_min,
      weakest_cycle_pair_mass_max = cycle_min_hi,
      stringsAsFactors = FALSE
    )
  }

  out <- bind_rows(rows) |>
    mutate(source = factor(source, levels = c("Agony", "WST", "SST", "DCSBM"))) |>
    arrange(source)

  readr::write_csv(out, file.path(OUT_DIR, "application_high_school_cycle_inspection.csv"))

  tex_rows <- character(0)
  for (i in seq_len(nrow(out))) {
    row <- out[i, ]
    source_key <- as.character(row$source)
    tex_rows <- c(tex_rows, sprintf(
      "%s & $%d$ & %s & $%d$ & %s & %s \\\\",
      POINT_SOURCE_LABEL[[source_key]],
      as.integer(row$K),
      fmt_count_pct(row$reversed_pairs, row$total_pairs),
      as.integer(row$tied_pairs),
      fmt_count_pct(row$cyclic_triples, row$total_triples),
      fmt_mass_range(row$weakest_cycle_pair_mass_min, row$weakest_cycle_pair_mass_max)
    ))
  }

  lines <- c(
    "% Auto-generated by scripts/analysis/build_application_supplement_tables.R",
    "% Do NOT edit by hand.",
    "\\begin{table}[htbp]",
    "\\centering",
    "\\small",
    "\\setlength{\\tabcolsep}{5pt}",
    "\\begin{tabular}{@{}lrrrrr@{}}",
    "\\toprule",
    "Point estimate & $K$ & Backward-majority pairs & Tied pairs & Cyclic triples & Weakest cyclic-pair mass \\\\",
    "\\midrule",
    tex_rows,
    "\\bottomrule",
    "\\end{tabular}",
    paste0(
      "\\caption{High-school comparison between the ordered empirical ",
      "forward-share matrix and the majority-cycle diagnostic. ",
      "Backward-majority pairs are unordered block pairs \\((k,\\ell)\\), ",
      "\\(k<\\ell\\), whose displayed forward share is below one half. ",
      "Cyclic triples are directed 3-cycles in the majority-flow graph. ",
      "The last column gives the range, across cyclic triples, of the ",
      "smallest pairwise edge count supporting that triple.}"
    ),
    "\\label{tab:high-school-cycle-inspection}",
    "\\end{table}"
  )
  writeLines(lines, file.path(OUT_DIR, "application_high_school_cycle_inspection.tex"))
}

build_psis_table()
build_cycle_table()
build_high_school_cycle_inspection_table()

cat("Wrote:\n",
    "  ", file.path(OUT_DIR, "application_psis_diagnostics.tex"), "\n",
    "  ", file.path(OUT_DIR, "application_cycle_diagnostics.tex"), "\n",
    "  ", file.path(OUT_DIR, "application_high_school_cycle_inspection.tex"), "\n",
    sep = "")
